server {
    listen 8094;
    listen [::]:8094;
    server_name _;

    root /var/www/cold-storage-wiki/current;
    index index.html;

    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;

    location / {
        try_files $uri $uri/ =404;
    }
}
